service/data-storage.yml
_This commit is a *proposal* of content structure. It modifies one page of the content as an example. It is backwards compatible with all current consumers of the content._
We now have the requirement to store this additional information:
This proposal adds two new attributes to the content:
- `servicePageLabel` on each question object: The label that will be shown before a supplier's response on a service page
- `filterLabel` to each question's `field` object: The label that will be shown alongside the checkbox when filtering
If `filterLabel` or `servicePageLabel` are omitted then the _intention_ is that the respective filter or response should not be rendered to the page. The implementation of this is left to the application consuming the content.
=> Add labels for use in filters and on service pages

service/networks-and-connectivity.yml, service/security/asset-protection-and-resilience.yml, service/security/audit-information-provision-to-consumers.yml, service/security/data-in-transit-protection.yml, service/security/identity-and-authentication.yml, service/security/separation-between-consumers.yml, service/terms-and-conditions.yml
It doesn't seem desirable or advisable for buyers to search for services which don't match any of the clearly-defined options. For example:
**Probably useful** to show only services that support *TLS 1.2 or later*
**Probably not useful** to show only that have *no encryption*
This commit hides the second kind of option by removing their `filterLabel` attribute.
Requires merging of https://github.com/alphagov/digital-marketplace-prototype/pull/7 for the effect to be visible.
=> Hide options for other/none/rest-of-world

g6/governanceFramework.yml
CESG noticed that we had misspelled [ISO27001](http://www.iso.org/iso/home/standards/management-standards/iso27001.htm) as ISO27**7**001. This commit fixes it.
=> Fix ISO27001 typo

g6/lot.yml, tests/schemas/question.json
This comes from the previous SSP. Using 'description' for the text underneath each button matches the naming on http://alphagov.github.io/digitalmarketplace-frontend-toolkit/forms/selection-buttons.html
=> Add content for the 'choose a lot' question

g6/codeLibraryLanguages.yml, g6/identityStandards.yml, g6/serviceTypesIaaS.yml, g6/serviceTypesSCS.yml, g6/serviceTypesSaaS.yml, g6/terminationCost.yml, tests/schemas/question.json
We should be strict about this because Python, for example, will let you do both of these:
```
for lot in "sass paas iaas" …
for lot in ["sass", "paas", "iaas"] …
```
but the behaviour will be subtly different.
This also fixes a mistake in the schemas which prevented this from being enforced.
=> Enforce array type for dependencies

g6/priceString.yml
Make the messages for min or max prices not being numbers identify the
field that is in error.
=> Make price errors more specific

g6/termsAndConditionsDocumentURL.yml
Currently the question for T&C document is a different style from other document upload questions - i.e:
This should make things look better.
=> Make t&c question the same style as other document questions

g7_declaration/SQ1-1a.yml, g7_declaration/SQ1-1cii.yml, g7_declaration/SQ1-1d-i.yml, g7_declaration/SQ1-1g.yml, g7_declaration/SQ1-1h.yml, g7_declaration/SQ1-1i-i.yml, g7_declaration/SQ1-1i-ii.yml, g7_declaration/SQ1-1j-i.yml, g7_declaration/SQ1-1j-ii.yml, g7_declaration/SQ3-1k.yml, g7_declaration/SQ4-1c.yml
This adds validation messages for the G7 supplier declaration form.
In addition to these error messages there is a default `answer_required` message for all non-optional fields set in the app. This is currently "This question is required".
cc/ @superroz
=> Add validation messages for G7 declaration

g7_declaration/PR5.yml
This was missed by the review of the [original pull request](https://github.com/alphagov/digitalmarketplace-ssp-content/pull/67).
=> Correct link URL to be local, not absolute

g7_declaration/SQ1-1o.yml, g7_declaration/SQ1-2b.yml
I wasn't sure about "You must enter..." vs. "Please enter...", but all the other declaration question messages (e.g. VAT number, DUNS number) use "You must..." so I went with that for emails too.
=> Add email validation error messages

g6/apiType.yml, g6/codeLibraryLanguages.yml, g6/identityStandards.yml
These are optional questions but were not marked as such, which will prevent users from being able to mark their service as complete unless they fill-in these optional questions.
=> Mark optional questions as optional

g7_declaration/SQ1-1h.yml, g7_declaration/SQ1-1j-i.yml
- Changed hint text to VAT question. There's also a story in pivotal to strip out the validation here.
- Added a 'none of the above' option to the licensed/member of a relevant organisation question for Canadian companies.
=> Content updates from clarification questions

g6/dataBackupRecovery.yml, g6/dataExtractionRemoval.yml, g6/datacentreTier.yml, g6/datacentresEUCode.yml, g6/datacentresSpecifyLocation.yml, g7_declaration/SQ1-1h.yml
This removes some unused stuff from content:
* VAT number validation message, as we no longer validate VAT numbers;
* `assuranceApproach: null` from Data Storage questions.
=> Bit of a tidy up

frameworks/digital-outcomes-and-specialists/messages/homepage-sidebar.yml, frameworks/g-cloud-7/messages/homepage-sidebar.yml, tests/schemas/messages.json
Isolating content which is dependent on:
- a framework
- the status of that framework
Changes messages on the home page as framework statuses change.  Means we don't have to mess about with feature flags or anything silly like that.  
Added a JSON schema because the tests were breaking, but there's very little in it because messages seem like bad things to try and overdetermine.
-
[>> Ralph's prototype displaying the messages](http://dm-prototype.herokuapp.com/states/homepage?dos.framework=open)
[>> Story on Pivotal](https://www.pivotaltracker.com/story/show/105005304)
=> [#105005304] Add homepage sidebar framework messages.

frameworks/digital-outcomes-and-specialists/questions/services/lot.yml
Initial descriptions copied from the digitalmarketplace-prototype.
Lot question is used to render the lot selection page with lot
descriptions for each lot.
=> Add digital-outcomes-and-specialists lot descriptions

frameworks/digital-outcomes-and-specialists/manifests/edit_submission.yml, frameworks/digital-outcomes-and-specialists/questions/services/serviceName.yml
Sets serviceName to be the first question so that every created
draft has a name to display in the service list, similar to G7.
Question is copied from the current prototype.
=> Add serviceName question for user research studios

requirements.txt, scripts/generate-schemas.py
Script loads the question files for the given lot and generates a schema
using predefined property templates for different question types.
Current limitations and workarounds:
* Script is using dmutils ContentLoader to get a list of questions and
`edit_submission` manifest is assumed to contain the full list of
service data questions
* Pricing fields are treated differently when added to the list of
required keys
* Assertion answer sets are hardcoded and need to be updated if the
content changes
* Question max length and word length limits are parsed from the
question validations. This should be replaced with `max_length`
and `max_length_in_words` question properties eventually.
Script outputs a JSON file with sorted keys and "required" list.
Script output matches the current G7 schema …
=> Add generate-schemas script to create JSON schemas from content files

frameworks/digital-outcomes-and-specialists/messages/homepage-sidebar.yml
On the 'coming' state I added:
``` If you already have an account you’ll be notified by email when Digital Outcomes and Specialists opens````
Fixed a typo on both states:
eg a discovery phase **or** an online billing application
to:
eg a discovery phase **for** an online billing application
Placeholder for ```Find out how to apply``` changed to ```Find out if your services are suitable``` and linked to corresponding blog post.
=> What to do if you have an account and link to blog

frameworks/digital-outcomes-and-specialists/manifests/edit_submission.yml, frameworks/digital-outcomes-and-specialists/questions/services/labAddressBuilding.yml, frameworks/digital-outcomes-and-specialists/questions/services/labAddressPostcode.yml, frameworks/digital-outcomes-and-specialists/questions/services/labAddressTown.yml
See: https://www.pivotaltracker.com/story/show/107188868
The story says to split the address into three fields, but the prototype page linked to has it over four fields (https://dm-prototype.herokuapp.com/states/studio-location)
I've gone with three, but we can iterate to four if necessary:
=> [#107188868] Split lab address into three separate fields

.travis.yml, README.md, frameworks/digital-outcomes-and-specialists/questions/services/agileCoach.yml, frameworks/digital-outcomes-and-specialists/questions/services/businessAnalyst.yml, frameworks/digital-outcomes-and-specialists/questions/services/communicationsManager.yml, frameworks/digital-outcomes-and-specialists/questions/services/contentDesigner.yml, frameworks/digital-outcomes-and-specialists/questions/services/deliveryManager.yml, frameworks/digital-outcomes-and-specialists/questions/services/designer.yml, frameworks/digital-outcomes-and-specialists/questions/services/developer.yml, frameworks/digital-outcomes-and-specialists/questions/services/performanceAnalyst.yml, frameworks/digital-outcomes-and-specialists/questions/services/portfolioManager.yml, frameworks/digital-outcomes-and-specialists/questions/services/productManager.yml, frameworks/digital-outcomes-and-specialists/questions/services/programmeManager.yml, frameworks/digital-outcomes-and-specialists/questions/services/qualityAssurance.yml, frameworks/digital-outcomes-and-specialists/questions/services/securityConsultant.yml, frameworks/digital-outcomes-and-specialists/questions/services/serviceManager.yml, frameworks/digital-outcomes-and-specialists/questions/services/technicalArchitect.yml, frameworks/digital-outcomes-and-specialists/questions/services/userResearcher.yml, frameworks/digital-outcomes-and-specialists/questions/services/webOperations.yml, requirements.txt, schemas/questions.json, scripts/generate-schemas.py, scripts/generate_dos_specialists_questions.sh
Generates JSON files to correctly validate services where a "at least one of" a group of questions have to be present.  For example, at least one specialist needs to be present for a service to validate, and a specialist consists of more than one related keys.
Needs pull request [#213](https://github.com/alphagov/digitalmarketplace-utils/pull/213) in utils to pass tests.
[>> Story on Pivotal](https://www.pivotaltracker.com/story/show/107188910)
As before, all of the possible keys a schema will accept need to be defined in the top-level `"properties"` dictionary, and then groups of related keys must be specified in their own schemas in under a top-level [`"anyOf"` key](http://json-schema.org/latest/json-schema-validation.html#anchor85). 
Kind of looks like this:
```json
{
"properties": { …
```
=> [#107188910] Generate JSON schemas which validate "at least one of" a group of questions.

frameworks/digital-outcomes-and-specialists/messages/homepage-sidebar.yml
Currently the absolute links break on preview - clicking them will take you to production, which means we can't use end-to-end functional testing on those links.
=> Making login/create account links on the homepage sidebar relative

frameworks/digital-outcomes-and-specialists/messages/dates.yml, frameworks/g-cloud-7/messages/dates.yml, schemas/messages.json
Ultimately these should be stored in the API but for the moment we don't know how many different dates there will be and it is therefore difficult to know what the right way of managing them is.
=> Add dates as messages

scripts/generate-schemas.py
Long price string without spaces break the layout and since there's
no reason to have them we just limit the strings accepted by the
JSON schema to 15 character before the decimal point and 5 after.
=> Limit schema price string to 15 digits before decimal point

frameworks/digital-outcomes-and-specialists/questions/services/lot.yml
Changes the lot question option labels to match the prototype text.
This means that lot question labels no longer match lot names, but
since the quesiton is only used for the submission lots page this
doesn't affect any other pages at the moment.
=> Add "Apply to provide" to dos lot links text

frameworks/digital-outcomes-and-specialists/manifests/declaration.yml, frameworks/digital-outcomes-and-specialists/questions/services/openStandardsPrinciples.yml, frameworks/digital-outcomes-and-specialists/questions/services/serviceName.yml
Our `markdown` filter doesn't insert newlines unless it sees two consecutive newlines. 
So I've added several where @sarahcunliffe pointed them out.
=> Add linebreaks for markdown interpreter

frameworks/digital-outcomes-and-specialists/questions/declaration/readUnderstoodGuidance.yml
[This](http://www.gov.uk/guidance/digital-outcomes-and-specialists-suppliers-guide) is where the suppliers guide will be.
It isn’t there yet.
--
https://www.pivotaltracker.com/story/show/106106748
=> Link to suppliers guide on GOV.UK

frameworks/digital-outcomes-and-specialists/manifests/edit_brief.yml, frameworks/digital-outcomes-and-specialists/questions/briefs/additionalTerms.yml, frameworks/digital-outcomes-and-specialists/questions/briefs/essentialRequirements.yml, frameworks/digital-outcomes-and-specialists/questions/briefs/evaluationType.yml, frameworks/digital-outcomes-and-specialists/questions/briefs/location.yml, frameworks/digital-outcomes-and-specialists/questions/briefs/niceToHaveRequirements.yml, frameworks/digital-outcomes-and-specialists/questions/briefs/organisation.yml, frameworks/digital-outcomes-and-specialists/questions/briefs/outcome.yml, frameworks/digital-outcomes-and-specialists/questions/briefs/specialist.yml, frameworks/digital-outcomes-and-specialists/questions/briefs/specialistRole.yml, frameworks/digital-outcomes-and-specialists/questions/briefs/workingArrangements.yml, schema_generator/__init__.py, scripts/generate-schemas.py, tests/test_generate_schema.py
This pull request sets up the back-end scaffolding needed in order to build a brief-creation form. 
Questions aren't finalised, but they are:
- based on those [in the prototype](http://dm-prototype.herokuapp.com/)
- all different field types: 
- `list`, `checkboxes`, `radios`, `text`, `textbox_large`
- different for different lots
- essential / optional
Changed some of the top-level schema-generation functions (to look for brief questions, and to appropriately name schemas generated for briefs) but nothing to do with the the actual generation logic.  
Therefore, JSON schemas generated for briefs are identical to what their equivalent service schemas would look like.
Means I didn't hardly do much additional testing and nothing to do with the ContentLoader needs changing.
[>> Story on …
=> [#111518510] Buyer can create a brief -- content repo

schema_generator/__init__.py, tests/test_generate_schema.py
When defining checkboxes or radio sets a value can be provided to each option as well as a label. If provided this is used as the value attribute of the option. This change updates the JSON schemas to use that value rather than the label if the value has been provided.
Props to @allait for showing me how to hypothesis.
=> Use option value in JSON schemas if available

frameworks/digital-outcomes-and-specialists/manifests/display_brief.yml
Adds a first-draft of the manifest for the `/digital-outcomes-and-specialists/opportunities/<id>` page.
Is a first draft of the page proposed in the prototype: http://dm-prototype.herokuapp.com/page/requirement/template-brief?key=outcomes.0.
=> Add manifest for briefs page

frameworks/digital-outcomes-and-specialists/questions/declaration/MI.yml, frameworks/digital-outcomes-and-specialists/questions/declaration/termsAndConditions.yml, frameworks/digital-outcomes-and-specialists/questions/declaration/termsOfParticipation.yml, frameworks/g-cloud-7/questions/declaration/AQA3.yml, frameworks/g-cloud-7/questions/declaration/PR1.yml, frameworks/g-cloud-7/questions/declaration/PR2.yml, frameworks/g-cloud-7/questions/declaration/SQC2.yml
An [earlier commit](https://github.com/alphagov/digitalmarketplace-frameworks/commit/2c747d2133ac1f7fbec34028805f1ea79802f3c4) added file type and size information to PDF download links.
This adds similar link text for the ZIP file downloads that I missed in the earlier commit.
As per @tombye's comment: 
"If we're linking to a document, it should include the file type and size as on www.gov.uk.
An example of what I mean at the bottom of: https://www.gov.uk/green-deal-energy-saving-measures/improvements-and-benefits-to-your-home"
=> Add file type and size to ZIP file download links

frameworks/digital-outcomes-and-specialists/questions/briefs/specialistRole.yml
@pcraig3 noticed the performance analytist and techical architect specialisms are recognised [specialisms a service can provide](https://github.com/alphagov/digitalmarketplace-frameworks/tree/master/frameworks/digital-outcomes-and-specialists/questions/services) but aren't available for briefs.
This adds them.
I've run the [scripts/generate-schemas.py](https://github.com/alphagov/digitalmarketplace-frameworks/blob/master/scripts/generate-schemas.py) script to update the schemas.
The updates have been put into this pull request:
https://github.com/alphagov/digitalmarketplace-api/pull/374
=> Add missing specialist roles to brief

Makefile, README.md, requirements_for_test.txt, setup.cfg, tests/test_generate_schema.py
A PEP8 error with a file from this repo was breaking the tests on the buyer app.
This adds PEP8 checking here to ensure this won't happen again and wraps it in a `Makefile` to make it consistent with the other apps.
=> Make tests better

frameworks/digital-outcomes-and-specialists/manifests/edit_brief.yml
Previously, our assumption had been that titles were of lesser importance/value than actually picking a location or role (arguably, it gets the buyer thinking of the important thing about their brief sooner), but now we don't know if that's a real thing.
@ralph-hawkins isn't here and the prototype starts with selecting a title, so let's do that.
=> Set title as the first question needed for creating a brief

frameworks/digital-outcomes-and-specialists/questions/briefs/questionAndAnswerSessionDetails.yml
the line 'the date and time of the session' has had '(this should happen within 1 week of publishing your requirements)' added to it.
=> content update so buyers know when they should hold their q+a session

frameworks/digital-outcomes-and-specialists/questions/briefs/summary.yml
Remove 'brief' from message 'Your answer must be no brief more than 50 words.'
=> Remove 'brief'

frameworks/digital-outcomes-and-specialists/manifests/edit_brief_response.yml
This is a fallback title no one should ever actually see, but it's still worth keeping it consistent from the way we talk about applying to opportunities in the buyer app.
=> Change "to an" to "for this"

frameworks/digital-outcomes-and-specialists/messages/dates.yml, frameworks/g-cloud-7/messages/dates.yml, frameworks/g-cloud-8/messages/dates.yml
Required to fix:
- https://www.pivotaltracker.com/story/show/119086793
- https://www.pivotaltracker.com/story/show/119075005
The markdown filter wraps values in `<p>` tags but we generally want to use dates inline and the `<p>` breaks the page layouts in the frontend.  So we're not going to use markdown for date strings.
=> Don't markdown dates

README.md, schema_generator/__init__.py, schemas/questions.json
Generates an array property for the dynamic list field and sets the items schema to match nested question fields.
Followup questions generate a subschema to validate that if a question was answered with 'Yes' then the followup question has to be answered too.
Schema generation supports multiple followup relationships within one group of dynamic_list nested questions, but it's likely that API error reporting will require some changes if this ever becomes a feature we need.
=> Add dynamic list and followup questions to schema generator

frameworks/g-cloud-9/questions/services/accessRestrictionsManagementAndSupport.yml, frameworks/g-cloud-9/questions/services/approachToResilience.yml, frameworks/g-cloud-9/questions/services/backupControls.yml, frameworks/g-cloud-9/questions/services/configurationAndChangeManagementProcesses.yml, frameworks/g-cloud-9/questions/services/dataExportHow.yml, frameworks/g-cloud-9/questions/services/dataSanitisationApproach.yml, frameworks/g-cloud-9/questions/services/endOfContractDataExtraction.yml, frameworks/g-cloud-9/questions/services/gettingStarted.yml, frameworks/g-cloud-9/questions/services/guaranteedAvailability.yml, frameworks/g-cloud-9/questions/services/howSharedInfrastructureIsKeptSeparate.yml, frameworks/g-cloud-9/questions/services/incidentManagementApproach.yml, frameworks/g-cloud-9/questions/services/informationSecurityPoliciesAndProcesses.yml, frameworks/g-cloud-9/questions/services/metricsTypes.yml, frameworks/g-cloud-9/questions/services/outageReporting.yml, frameworks/g-cloud-9/questions/services/placeholderStandardsAndCertifications.yml, frameworks/g-cloud-9/questions/services/resellerRelationship.yml, frameworks/g-cloud-9/questions/services/scalingApproach.yml, frameworks/g-cloud-9/questions/services/scalingPricingStructure.yml, frameworks/g-cloud-9/questions/services/securityGovernanceApproach.yml, frameworks/g-cloud-9/questions/services/supportLevels.yml, frameworks/g-cloud-9/questions/services/supportResponseTimes.yml, frameworks/g-cloud-9/questions/services/usingTheAPI.yml, frameworks/g-cloud-9/questions/services/usingTheCommandLineInterface.yml, frameworks/g-cloud-9/questions/services/usingTheWebInterface.yml, frameworks/g-cloud-9/questions/services/virtualisationTechnologiesUsed.yml, frameworks/g-cloud-9/questions/services/vulnerabilityManagementApproach.yml
e.g. if it's a 50 word limit then the key should be `under_50_words`.
Not planning to bump the version here as lots more changes coming soon, I know.
But validation won't work as expected for these questions in Preview right now.
=> Validation keys need to match allowed word counts

README.md, schemas/manifests.json, schemas/questions.json
(support for this already exists in content loader)
Please review my regex - the basic intention is "allow alphanumeric chars and dashes, not beginning or ending with a dash, but including the possibility of a single char slug".
=> schemas: allow "slug" attributes for manual slug specification

frameworks/g-cloud-9/questions/services/serviceInterfaceAccessibility.yml, frameworks/g-cloud-9/questions/services/serviceInterfaceAccessibilityDescription.yml, frameworks/g-cloud-9/questions/services/serviceInterfaceTesting.yml
- now the 'testing' question will only appear if the service does not
meet an accessibility standard, as intended.
=> Software accessibility question had wrong dependency set-up

frameworks/g-cloud-9/search_mapping.json, schema_generator/search.py, scripts/generate-search-config.py, tests/test_generate_search_config.py
Script to generate Elasticsearch mapping for framework, inc transformations.
- Most of the mapping comes, unchanged, from a template file which
has been copied from the Search API i.e. mappings/services.json .
- The main addition is of a 'transformations' node, which the
Search API will use to preprocess the incoming service data before
passing it on to Elasticsearch.
- The only transformation we add so far is one that indexes parent
categories relating to select subcategories. This is denormalization
is done purely in the index.
- Other meta information is added so that it's clear that the file
in the Search API is no longer the original, and should not be
edited by hand.
- Brings in new version of Content Loader, which now depends on dm-
utils library. …
=> Elasticsearch mappings and transformation generation

schema_generator/search.py, tests/test_generate_search_config.py
mapping generator with new more forward-compatible syntax.
- the syntax is now more consistent with Elasticsearch's "ingest node
processor" feature.
https://trello.com/c/etYh34Zs/341-fixing-software-parent-categories
=> Updated mapping generator 

schema_generator/search.py
Preserve the order of the transformations per the source yaml
- somehow this was lost previously by mistake
- effectively this is alphabetical order
https://trello.com/c/etYh34Zs/341-fixing-software-parent-categories
=> Preserve the order of the transformations

frameworks/g-cloud-9/search_mapping.json
As above... Add the 'serviceDescription' field to the search mapping to enable indexing of said field in ES.
=> Add 'serviceDescription' to search mapping

schema_generator/search.py
As above. Need to allow `radios` questions to be checked for derived_from transformations when generating search schemas.
=> Enable transformation of radios questions for schema generation

frameworks/g-cloud-9/search_mapping.json, schema_generator/search.py
All part of story https://trello.com/c/5oIKvS1s/100-search-service-for-briefs-plus-indexing-script
Also update schema generator to be able to cope with template-provided transformations.
See also https://github.com/alphagov/digitalmarketplace-search-api/pull/116 for equivalent search api changes.
=> search mappings: update g-cloud-9 search mapping to new search api mapping scheme

frameworks/g-cloud-10/questions/services/securityTesting.yml, frameworks/g-cloud-10/questions/services/securityTestingAccreditations.yml, package.json
For this ticket: https://trello.com/c/Khm9AS0X/68-re-add-cyber-for-g-cloud-10
Suppliers with some specific security accreditations were barred from supplying through G-Cloud and instead directed to the "Cyber framework" instead.  But for G-Cloud 10 they will be allowed.
So we have been told to "re-add cyber" for G-Cloud 10.  
No-one really knows what this means, so I've had a go at figuring it out here.
Trawling the history of this repo I found two security-related questions that were deleted mid way during development of G-Cloud 9.  They look like this:
Looking at the way the security questions ended up for G-Cloud 9 launch it looks to me like these questions are unnecessary as full questions, and the same information can be collected from suppliers with the addition of two checkboxes to …
=> Add more cyber security accreditations

frameworks/g-cloud-10/questions/services/securityTesting.yml, frameworks/g-cloud-10/questions/services/securityTestingAccreditations.yml, package.json
Reverts alphagov/digitalmarketplace-frameworks#505
Correct changes are in https://github.com/alphagov/digitalmarketplace-frameworks/pull/511
=> Revert "Add more cyber security accreditations"

frameworks/g-cloud-10/questions/services/accreditationsOther.yml, frameworks/g-cloud-10/questions/services/accreditationsOtherList.yml, frameworks/g-cloud-10/questions/services/multiqAccreditationsOther.yml, frameworks/g-cloud-10/questions/services/securityGovernanceAccreditation.yml, frameworks/g-cloud-10/questions/services/securityTestingWhatOther.yml, package.json
Change language to consistently use 'certification' rather than
'accreditation' where appropriate (i.e. generally where 'accreditation'
is used as a noun or where we do not need to repeat the same/similar
word close together).
=> Change to certification noun

frameworks/g-cloud-10/metadata/copy_services.yml, package.json
Some questions specify an ID to use in place of the filename. We had
incorrectly stored the filename in all instances rather than the ID,
where it was given. This corrects that so the data is correctly copied
across for all questions that are equivalent.
Bumps version to 11.5.2
=> Update questions to copy

frameworks/g-cloud-10/messages/dates.yml, frameworks/g-cloud-10/questions/declaration/MI.yml, frameworks/g-cloud-10/questions/declaration/servicesHaveOrSupport.yml, frameworks/g-cloud-10/questions/declaration/termsAndConditions.yml, frameworks/g-cloud-10/questions/declaration/termsOfParticipation.yml, package.json
We need to have the correct dates stored in our frameworks repository
for G-Cloud 10 stages. These are sourced from
https://www.gov.uk/guidance/what-to-do-and-when-for-g-cloud-10
Also add anchors to links to the G-Cloud 10 framework dashboard documents.
=> Update G-Cloud-10 dates

CHANGELOG.md, frameworks/digital-outcomes-and-specialists-2/messages/dates.yml, frameworks/digital-outcomes-and-specialists-3/messages/dates.yml, frameworks/digital-outcomes-and-specialists/messages/dates.yml, frameworks/g-cloud-10/messages/dates.yml, frameworks/g-cloud-6/messages/dates.yml, frameworks/g-cloud-7/messages/dates.yml, frameworks/g-cloud-8/messages/dates.yml, frameworks/g-cloud-9/messages/dates.yml, package.json, requirements.txt, schemas/messages.json
We are migrating framework lifecycle event dates/times to the API and
storing them in machine format, rather than as strings for humans. This
should decrease any risk of errors creeping in and also bring us back to
a single source of truth.
Frontends that use frameworks will need to stop loading dates from this
frameworks repo and start using dates from the API.
Bump to version 12.0.0
=> Remove `dates.yml` files

frameworks/g-cloud-10/messages/become-a-supplier.yml, package.json
For this trello ticket: [https://trello.com/c/7P1cRFqt](https://trello.com/c/7P1cRFqt)
There will be a corresponding PR on the supplier frontend to pull these changes in once merged.
The content on the `become a supplier` page is wrong, and needs updating.
At the time of writing G-Cloud 10 is `pending` and so the changes to
`coming` and `open` will never be seen. I'm updating them too for
consistency and in case this file is copied to a new
iteration of the framework in future.
=> Update content for `become a supplier` messages

frameworks/g-cloud-10/messages/urls.yml, package.json
We display this link to users during standstill as they need to be able
to view the rest of the framework agreement (we only provide section 1 - 
the 'signature page').
=> Update framework agreement direct pdf link

frameworks/g-cloud-10/search_mappings/services.json, scripts/generate-search-config.py
The version of the frameworks repo is no longer defined in
`VERSION.txt`, instead it's in `package.json`
This also update the G10 search_mapping to have a `max_result_window` of
25000. This is because we have 24950 ish services to index.
=> Update `generate-search-config` for G10

package.json
Forgot to bump version in PR 526: https://github.com/alphagov/digitalmarketplace-frameworks/pull/526
=> Bump version to 12.1.2

CHANGELOG.md, frameworks/g-cloud-10/messages/urls.yml, frameworks/g-cloud-9/messages/urls.yml, package.json, schemas/messages.json
Links to the buyers guide are no longer required in the frameworks repo, as it makes sense to hard-code these links into our content in our template. The content and the guide are inextricably linked, and are not specific to the framework but relate to the 'Direct Award' buying process.
https://trello.com/c/7wlBbGU0/138-add-step-3-assessing-your-service-and-badges
=> Remove buyers' guide links from the messages schema.

frameworks/digital-outcomes-and-specialists-3/metadata/following_framework.yml, package.json, schemas/metadata.json
For [this trello ticket](https://trello.com/c/Msvn4HAz).
We're introducing a custom error page for suppliers for when
applications close and they try to follow a link that is no longer
available. Editing a service for example.
Previously they've been served a generic error page which is unhelpful.
Now they'll get an error page with more information, and some brief
details about when the next framework is expected. That's what this
content is for.
=> Add following_framework metatdata for DOS3

Makefile, default.nix
Python36 includes the venv module which means we no longer need virtualenv to be installed on the development system
=> Remove requirement on virtualenv

frameworks/g-cloud-11/messages/homepage-sidebar.yml, package.json
Trello: https://trello.com/c/WnalAx1D/386-set-g11-to-coming-on-staging
Time to put the proper year on the homepage, not 2525.
Also includes expected application closing date (still awaiting final confirmation).
Will need to be pulled into Buyer FE.
=> G11 homepage dates

CHANGELOG.md, package.json, requirements-dev.txt, schema_generator/assessment.py, schema_generator/validation.py, tests/test_generate_validation_schema.py
These changes update the number_property method and associated tests. These changes are a part of updating our JSON schema to version 7, which expects exclusiveMaximum to be a number rather than a boolean.
In updating the `number_property` function I found the `not limits.get('integer_only')` pattern confusing, and replaced it with a variable that explains what we're actually checking.
=> Update function and tests for JSON schema V7

CHANGELOG.md, frameworks/g-cloud-10/search_mappings/services.json, frameworks/g-cloud-11/search_mappings/services.json, frameworks/g-cloud-9/search_mappings/services.json, package.json
Ticket: https://trello.com/c/uTA0PcGF
`include_in_all` is deprecated in Elasticsearch 5.6 and has been [removed][1] in Elasticsearch 6.0.
We were using `include_in_all: false` for the serviceIdHash as we didn't want people to be able to search by ID hash, but this option is now no longer available.
I'm currently looking into whether this will actually affect our search; I'm not sure if we ever search `_all` directly or indirectly. If we do we may have to decide whether we care about the hash being searchable because as far as I know there is no easy way to replicate the `include_in_all: false` behaviour in Elasticsearch 6.
[1]: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-6.0.html#_the_literal_include_in_all_literal_mapping_parameter_is_now_disallowed
=> Remove deprecated field `include_in_all`

frameworks/g-cloud-11/messages/homepage-sidebar.yml, frameworks/g-cloud-11/questions/declaration/canProvideFromDayOne.yml, frameworks/g-cloud-11/questions/declaration/modernSlaveryReportingRequirements.yml, frameworks/g-cloud-11/questions/declaration/modernSlaveryStatementOptional.yml, frameworks/g-cloud-11/questions/declaration/understandHowToAskQuestions.yml, frameworks/g-cloud-11/questions/services/managementAccessAuthentication.yml, frameworks/g-cloud-11/questions/services/publicSectorNetworksTypes.yml, frameworks/g-cloud-11/questions/services/serviceInterfaceAccessibility.yml, frameworks/g-cloud-11/questions/services/serviceInterfaceTesting.yml, package.json
Trello: https://trello.com/c/5CzbmwiW/407-bug-fixes-for-the-supplier-declaration-journey
Fixes following QA:
- some followup questions were not hidden/shown
- ModernSlavery guidance links needed fixing and opening in a new tab
- Revised application dates (still awaiting final-final-final confirmation, obviously)
These changes will require the API validation schemas to be regenerated - PR incoming for that.
=> G11 content fixes

requirements.txt
This is only really used for testing, but it's good to keep it up-to-date.
I also had to bump dmutils, as it's a requirement of dmcontent.
=> Update digitalmarketplace-content-loader from 4.6.0 to 5.2.0

frameworks/g-cloud-11/manifests/display_service.yml, frameworks/g-cloud-11/manifests/edit_service_as_admin.yml, package.json
While doing the manual spaniel I remembered that other manifests use service questions too, and we renamed one of the questions (`energyEfficientDatacentres` became `multiqEnergyEfficiency`) and added a new one (`energyEfficientDatacentresDescription `).
These manifests are used in the Admin and Buyer FEs.
=> Update other manifests with service changes

frameworks/g-cloud-11/questions/declaration/understandHowToAskQuestions.yml, package.json
Trello: https://trello.com/c/wgdqi2gJ/668-g-11-declarations-questions-update-clarification-deadline
The old date is the clarification question answers publish date, not the deadline for asking.
=> Update clarification question deadline

frameworks/g-cloud-11/metadata/copy_services.yml, package.json
Trello: https://trello.com/c/2IUa5FqD/676-launchcloud-error-with-g-cloud-11-application-process
We updated a dependency question to be triggered on a response value of `other` rather than `true`. Where users had copied their answers **and** previously responded `true`, validation was failing every time they tried to save their application because the dependent questions was triggering but contained no answer. This offers a fix for future users by not including responses to this question when they copy their previous declaration.
=> Exclude managementAccessDescription from copy_services

frameworks/g-cloud-11/questions/declaration/employersInsurance.yml, package.json
Trello: https://trello.com/c/1YUXLv7P/473-remove-unnecessary-clause-from-declaration-question
CCS and the G11 team agree that the following answer needs to be changed:
`Yes - your organisation has, or will have in place, employer’s liability insurance of at least $5 million and you will provide certification before the framework is awarded.`
To:
`Yes - your organisation has, or will have in place, employer’s liability insurance of at least $5 million`
The suppliers don't need to provide certification (CCS don't ask for it, and no-one provided it for G10!). Removing the clause should not cause a disadvantage to any suppliers.
=> Remove unnecessary clause from G11 declaration question

frameworks/g-cloud-11/questions/declaration/employersInsurance.yml, package.json
Trello: https://trello.com/c/1YUXLv7P/473-remove-unnecessary-clause-from-declaration-question
This will allow any suppliers who have already answered the question with the old text value to still pass the framework validation. We can remove this for DOS4.
=> Fix pass/fail for employer insurance question

frameworks/g-cloud-11/questions/declaration/employersInsurance.yml, package.json
These are proving to be too problematic, and it's something we probably shouldn't push out during an application phase. It would also result in us forever having slightly complicated dirty data for G11 declarations.
=> Revert G11 declaration "employers liability" question changes

frameworks/g-cloud-11/messages/homepage-sidebar.yml, package.json
The G11 application closing date has been extended to 5pm BST 22nd May 2019 (as per email already sent to suppliers). The home page content needs to be updated to reflect this.
Will need to be pulled into the Buyer FE.
=> Update G11 closing date

frameworks/g-cloud-11/questions/declaration/modernSlaveryReportingRequirements.yml, package.json, schema_generator/assessment.py, tests/test_generate_assessment_schema.py
Trello: https://trello.com/c/9PHHg4X3/509-generate-g11-declaration-assessment-schema-ko-w-kat
The `modernSlaveryReportingRequirements` question has an associated `mitigatingFactors3` question - it's a discretionary fail if users answer 'False'.
`modernSlaveryReportingRequirements` is also a sub question of `multiqModernSlavery`, a `multiquestion` type - the assessment schema can now handle this when generating the pass/fail schema. It's a fairly crude fix but we are unlikely to have more than one level of nested questions.
Generates this schema: https://github.com/alphagov/digitalmarketplace-scripts/pull/380
=> Assessment schema can handle multiquestion type declaration questions

package.json, schema_generator/validation.py
Trello: https://trello.com/c/kTVN6PlQ/532-clone-dos4-content
- Adds DOS4 to the list of schemas to be generated (see https://github.com/alphagov/digitalmarketplace-api/pull/936 for the output)
- Refactored the schema generation functions to be more DRY. We can't really fetch the framework info from the DB as we want this repo to be independent of the API (thankfully the lot/slug data is very unlikely to change).
=> DOS4 service and model validation schemas

frameworks/digital-outcomes-and-specialists-4/questions/services/accessibleApplicationsOutcomes.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/accessibleApplicationsSpecialists.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/bespokeSystemInformation.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/dataProtocols.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/helpGovernmentImproveServices.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/openStandardsPrinciples.yml, package.json
https://trello.com/c/kTVN6PlQ/532-clone-dos4-content
Adds validation for the mandatory questions on the DOS4 services, including the new accessibility questions. 
This means that the supplier must answer 'Yes' in order to proceed with adding the service (early feedback!) rather than waiting for us to run the pass/fail validation after applications have closed (when it's a bit late for them to do anything about it). 
I will re-generate the API schemas once this gets a thumbs-up.
=> Accessibility questions must be answered 'Yes'

frameworks/digital-outcomes-and-specialists-4/questions/declaration/MI.yml, frameworks/digital-outcomes-and-specialists-4/questions/declaration/termsAndConditions.yml, frameworks/digital-outcomes-and-specialists-4/questions/declaration/termsOfParticipation.yml, package.json
These got missed off for some reason. The bookmarks jump to the legal docs section of the supplier's application dashboard.
=> Fix DOS4 legal document links

frameworks/digital-outcomes-and-specialists-4/manifests/declaration.yml, package.json
Trello: https://trello.com/c/BZ1PRdXo/567-update-text-what-it-means-to-be-on-digital-outcomes-and-specialists-4
One of the questions now requires the answer to be 'no', so the advice needs to change. Content has been provided by Stefan. The `[[questionName]]` values resolve to the question numbers.
=> Reword declaration section intro

frameworks/digital-outcomes-and-specialists-4/questions/declaration/mitigatingFactors.yml, frameworks/digital-outcomes-and-specialists-4/questions/declaration/mitigatingFactors2.yml, frameworks/digital-outcomes-and-specialists-4/questions/declaration/mitigatingFactors3.yml, package.json, schemas/questions.json
https://trello.com/c/Bw46fBz5/559-declaration-questions-for-mitigatingfactors-have-no-maxlengthinwords
Adds maximum word and character limits to DOS4 free text questions. 500 words is the limit agreed by us and CCS (the 5000 character limit follows our convention of having a 10:1 character:word ratio elsewhere).
The validation itself will take place in the Supplier FE (separate PR incoming).
=> Add max word limits to textbox declaration questions

frameworks/digital-outcomes-and-specialists-4/manifests/declaration.yml, package.json
Trello: https://trello.com/c/BZ1PRdXo/567-update-text-what-it-means-to-be-on-digital-outcomes-and-specialists-4
Testing revealed that the supplier FE's CSS sets unordered lists to `list-style: none` in declaration section descriptions. So we have to hardcode some HTML into the description to explicitly include `class="list-bullet"`. We do this in a few places throughout the frameworks repo - I remember discussion about improving this a couple of years ago, but we haven't found a better solution so far.
(Skipping v16.0.5 with the hope that https://github.com/alphagov/digitalmarketplace-frameworks/pull/581 will get merged first)
=> Hardcode unordered list in declaration description

frameworks/digital-outcomes-and-specialists-4/questions/declaration/mitigatingFactors3.yml, package.json
a) the error message shouldn't show the field name in square brackets!
b) I answered 'no', not 'yes'!
The question number doesn't show up unlike for other similar error messages, because this is a nested question and it isn't numbered.
=> Bugfix: modern slavery mitigating factors error message

frameworks/digital-outcomes-and-specialists-4/manifests/edit_brief.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/evaluationTypeOutcomes.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/evaluationTypeParticipants.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/evaluationTypeSpecialists.yml, package.json
https://trello.com/c/S1kIwe05
Once brought through to the briefs frontend this goes from looking like
for digital outcomes in the initial state to 
with similar changes for digital specialists and UR participants.
=> dos4 briefs evaluationType* questions: remove before_summary_value, change content to make it clearer these are additional

frameworks/digital-outcomes-and-specialists-4/questions/briefs/evaluationTypeOutcomes.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/evaluationTypeParticipants.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/evaluationTypeSpecialists.yml, package.json
https://trello.com/c/57tHAqi9
From
to
It was thought the previous wording could be confusing because it all
appears below the heavy text "Optional".
This changes the wording, I think for the better - others opinions?
=> dos4 brief evaluationType* questions: improve opening text of question_advice

frameworks/g-cloud-11/messages/urls.yml, package.json
https://trello.com/c/J16FwsPb/939-customer-benefits-records-form-link
To replace the broken link in the G-Cloud saved search page (section 5 here https://www.digitalmarketplace.service.gov.uk/buyers/direct-award/g-cloud/start).
=> Bump version to 16.1.2

frameworks/g-cloud-11/questions/services/serviceCategoriesSupport.yml, package.json
https://trello.com/c/li12EojM/62-g-cloud-search-results-mapping-is-mis-categorising-a-filter
Part of the G-Cloud search mapping is generated from the `serviceCategories` question. A typo in this content has led to the `planningService` category being mapped to `setupAndMigrationService` services. 
Tested by running `./scripts/generate-search-config.py g-cloud-11 services`, which generates the correct mapping. This will be committed to the Search API in a separate PR (incoming!).
=> Fix PlanningService G-Cloud search mapping

.gitignore, .npmrc, .yarnrc, README.md, package-lock.json
We do not need to depend on Yarn as npm is Nodes default package manager and we use npm to install yarn. npm does everything yarn does now.
This commit mainly updates the manual but it also replaces `.yarnrc` with `.npmrc`.
Trello ticket: https://trello.com/c/RrpjQDJi/278-replace-yarn-with-npm
=> Remove Yarn in favour of npm

frameworks/digital-outcomes-and-specialists-4/questions/briefs/backgroundInformation.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/endUsers.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/outcome.yml, package-lock.json, package.json
https://trello.com/c/YELMUI7V/316-buyer-questions-should-have-longer-word-limit
3 buyer questions have been updated:
`Why the work is being done`
`Who the users are and what they need to do`
`Problem to be solved`
Will require a corresponding PR in the API (still in progress) to provide the correct validation (it will return the new error type `under_200_words`).
=> Increase word lengths for some buyer questions

frameworks/g-cloud-11/messages/urls.yml, package-lock.json, package.json
Ticket: https://trello.com/c/nY41xU2U/105-modify-copy-and-change-url-for-customer-benefits-record-form
CCS have changed the process for submitting a customer benefits record, it is now done by Google Form, so we need to update the link.
I believe CCS are also no longer using the customer benefits record email address, however until I've got confirmation on that from product I'm going to leave the current email address in.
This is needed before we can merge https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/950
=> Update URL for G-Cloud Customer Benefits Record

CHANGELOG.md, frameworks/g-cloud-11/messages/urls.yml, package-lock.json, package.json
Ticket: https://trello.com/c/nY41xU2U/105-modify-copy-and-change-url-for-customer-benefits-record-form
CCS no longer use this email address (customer benefit records are now submitted via Google Form, see #595), so we can remove this metadata from the G-Cloud framework.
=> Remove customer benefits record email

.travis.yml, package.json, requirements-dev.txt, requirements.txt, schema_generator/validation.py, tests/test_generate_validation_schema.py
https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
- Enabled Travis checks for 3.7 and 3.8
- Bumps content loader, utils and python-json-logger
- Updated PyYaml and flake8 (some minor whitespace fixes needed)
Also had to bump one of our test utils, `hypothesis` (and `pytest`). We were three major version bumps behind, and there were a lot of breaking changes. However our test data generation for this repo is pretty simple, so it worked with a few tweaks. For one test I did have to bump down the max size and suppress a warning about it being too slow to get it to work on all three Python versions, but I don't think that's a huge problem (happy to be convinced otherwise).
=> Enable Travis checks for Python 3.7 and 3.8

script_helpers/clone_helpers.py, scripts/clone-latest-framework.py, tests/test_clone_latest_framework.py
Automates some of the initial steps here: https://alphagov.github.io/digitalmarketplace-manual/content-and-frameworks/adding-frameworks.html#id2
It's verbose/non-DRY in places, to try and keep visibility of the different files being edited.
Tested with G-Cloud 12 and DOS 5, but not exhaustively.
Scope for more unit tests to be added at a later date 😸
=> Helper script for cloning framework content from a previous iteration

script_helpers/clone_helpers.py, tests/test_clone_latest_framework.py
https://trello.com/c/ePgvYRGr/256-clone-framework-content-just-clone-it-with-kats-script
We added this manually for G12, to make it obvious that the URLs should be reviewed.
Adds a test that mocks the file reads/writes - a bit verbose but hopefully clarifies what `yaml.dump()` is doing in the script.
=> Use file URL placeholders in framework cloning script

frameworks/digital-outcomes-and-specialists-4/questions/declaration/modernSlaveryReportingRequirements.yml, frameworks/g-cloud-11/questions/declaration/modernSlaveryReportingRequirements.yml, frameworks/g-cloud-12/assessment/declaration/extra.schema.json, frameworks/g-cloud-12/questions/declaration/modernSlaveryReportingRequirements.yml, requirements-dev.txt, schema_generator/assessment.py, schemas/questions.json, tests/test_generate_assessment_schema.py
This is to fulfil https://trello.com/c/kbTzccXb
Firstly I discovered that the "definite pass" G11 declaration answer used in the tests _wasn't_ a definite pass - it had missed out on some field renames/updates/splits since G10, but hadn't detected the "wrongness" because the generated schemas didn't `require` answers for any fields. So the first thing I did was make all assessed questions _by default_ required. I needed to make it possible to override this in the question yaml because of `modernSlaveryReportingRequirements`, which is the one exception.
Interestingly, the purpose of this `required` setting is **only** to help guarantee we keep the content, the test's "definite pass" candidate and the supplier frontend's custom declaration code in sync. We don't actually rely on it to …
=> assessment schema improvements

frameworks/g-cloud-12/messages/homepage-sidebar.yml, frameworks/g-cloud-12/questions/declaration/canProvideFromDayOne.yml, frameworks/g-cloud-12/questions/declaration/understandHowToAskQuestions.yml, package.json
https://trello.com/c/Hbojps0X/265-check-all-dates-in-content-for-g12-2
Dates now confirmed and published on GOV.UK: https://www.gov.uk/guidance/what-to-do-and-when-for-g-cloud-12
=> G-Cloud 12 dates

frameworks/g-cloud-12/questions/declaration/modernSlaveryReportingRequirements.yml, frameworks/g-cloud-12/questions/declaration/modernSlaveryStatement.yml, frameworks/g-cloud-12/questions/declaration/modernSlaveryStatementOptional.yml, frameworks/g-cloud-12/questions/services/pricingDocumentURL.yml, frameworks/g-cloud-12/questions/services/serviceDefinitionDocumentURL.yml, frameworks/g-cloud-12/questions/services/sfiaRateDocumentURL.yml, frameworks/g-cloud-12/questions/services/termsAndConditionsDocumentURL.yml, package-lock.json, package.json
https://trello.com/c/Rtcc6oi6/316-add-link-to-guidance-on-making-accessible-pdfs-on-application-5-places
We want to provide suppliers with guidance on uploading accessible documents.
Paired with @NoraGDS on the content.
There are 6 questions that involve file uploads:
1) Modern Slavery Statement (for suppliers with < £36m turnover) 
2) Modern Slavery Statement (for suppliers with >= £36m turnover)
3) Service definition document
4) Terms and conditions document
5) SFIA rate card 
6) Pricing document
=> G12 file upload guidance

frameworks/g-cloud-12/metadata/copy_services.yml, package-lock.json, package.json
https://trello.com/c/OZT4aPjn/367-copying-services-some-missing-fields
We reinstated some of the fields during the initial clone of the G12 content (https://github.com/alphagov/digitalmarketplace-frameworks/pull/599), but some got missed. This caused a bug, because we reintroduced `energyEfficientDatacentres`, but not `energyEfficientDatacentresDescription` (a dependent question).
There are also a few fields from G9 that never made it into the G11 copy list! See ticket for details.
=> Additional copy_services fields 

frameworks/g-cloud-12/messages/homepage-sidebar.yml, package-lock.json, package.json
https://trello.com/c/FmDeNVc2/370-add-3pm-gmt-to-homepage
To manage supplier expectations on opening day, let's include the opening time on the home page sidebar:
This version will need to be pulled into the Buyer FE.
=> Include opening time on homepage

frameworks/g-cloud-11/manifests/display_service.yml, frameworks/g-cloud-12/manifests/display_service.yml, package-lock.json, package.json
https://trello.com/c/BuMK8EoJ/1535-service-interface-info-bug
The `serviceInterface` and `serviceInterfaceDescription` questions were introduced in G-Cloud 11. Suppliers filled out the details on Supplier FE during applications as normal. However the fields weren't included in the manifest for displaying live services on the Buyer FE. 
I've updated the manifests for G11 and G12 and tested that the fields show as expected in the 'Using the service' section:
=> Include missing Service interface question on display service manifest

frameworks/g-cloud-12/messages/homepage-sidebar.yml, frameworks/g-cloud-12/questions/declaration/canProvideFromDayOne.yml, frameworks/g-cloud-12/questions/declaration/understandHowToAskQuestions.yml, package-lock.json, package.json
https://trello.com/c/uOuaPydJ/465-update-closing-date-for-g12-on-dmp-homepage
This is a first pass at updating the dates for G-Cloud 12. I may have missed some.
=> Update G-Cloud 12 dates

frameworks/digital-outcomes-and-specialists-4/questions/briefs/locationOutcomes.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/locationParticipants.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/locationSpecialists.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/agileCoachLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/businessAnalystLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/communicationsManagerLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/contentDesignerLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/dataArchitectLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/dataEngineerLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/dataScientistLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/deliveryManagerLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/designerLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/developerLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/outcomesLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/performanceAnalystLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/portfolioManagerLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/productManagerLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/programmeManagerLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/qualityAssuranceLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/recruitLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/securityConsultantLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/serviceManagerLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/technicalArchitectLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/userResearcherLocations.yml, frameworks/digital-outcomes-and-specialists-4/questions/services/webOperationsLocations.yml, package.json
This removes the ONS link as per https://trello.com/c/6b806g3r/40-remove-map-pdf-from-dos-brief-where-supplier-will-work
(I also removed it from the supplier questions, as it is assumed we would not want these links either in future iterations of the framework)
=> remove ONS link from DOS4 framework

frameworks/digital-outcomes-and-specialists-4/questions/briefs/culturalFitCriteriaOutcomes.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/culturalFitCriteriaSpecialists.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/essentialRequirementsOutcomes.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/essentialRequirementsParticipants.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/essentialRequirementsSpecialists.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/niceToHaveRequirementsOutcomes.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/niceToHaveRequirementsParticipants.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/niceToHaveRequirementsSpecialists.yml, frameworks/digital-outcomes-and-specialists-4/questions/briefs/questionAndAnswerSessionDetailsSpecialists.yml, package-lock.json, package.json
https://trello.com/c/X4vKC3Bv/112-2-apply-govuk-frontend-styles-to-frameworks-content-for-the-create-a-dos-opportunity-journey
We shouldn't really be using bold text in the places that we are, really - the Design System says "[use bold sparingly](https://design-system.service.gov.uk/styles/typography/)".
I've converted the examples below to headings, as that will give the same font size/weight as the other headings on the page (which is what we have currently anyway).
=> Use headings instead of bold text

script_helpers/clone_helpers.py, scripts/clone-latest-framework.py, tests/test_clone_latest_framework.py
https://trello.com/c/WBjRZd14/80-2-frameworks-repo-copyservices-list-exclude-rather-than-include-fields
Updates the framework-cloning script to support questions to exclude from service copying.
- Assumes 'exclude' is the default
- Will not copy questions if the previous iteration doesn't match the copying method (i.e. DOS4 is 'questions_to_copy', so if the script was run to generate DOS5, it would produce an empty `questions_to_exclude`, ready for someone to fill in manually once we know what's to be excluded).
- If the copying methods match, clone as normal
Also did some tidying around the tests. 
These changes are only for a script, so we don't need to update the version number (as this code isn't used by the apps).
=> Exclude questions when cloning framework content

frameworks/g-cloud-12/questions/services/standardsISOIEC27001When.yml
Trello: https://trello.com/c/lwJW7PvN/288-2-create-dos5-service-schemas
The limit is 100 in digitalmarketplace-api (https://github.com/alphagov/digitalmarketplace-api/blob/f71d124/json_schemas/services-g-cloud-12-cloud-software.json#L3067), but 50 in this repo.
It was originally 100, but was changed in 62d3375f1baea0bbf8b3dbb1c5b1876694868adc. This change to 50 looks like a copy-paste error to me, so reverting to 100 is the right thing to do.
I don't know, but would be surprised if increasing the limit has any negative effects.
=> Revert accreditation date field to 100 char limit

tests/test_generate_validation_schema.py
The [`integers`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.integers) strategy allows us to specify min and max values (inclusively). Thus, we can use those instead of assuming. This should make those tests slightly faster, and reduce the risk of Hypothesis failing altogether because it can't find enough good examples.
Might reduce the risk of future [build failures](https://travis-ci.com/github/alphagov/digitalmarketplace-frameworks/builds/184405782)
=> Assume less in tests

frameworks/g-cloud-12/messages/urls.yml, package-lock.json, package.json
https://trello.com/c/TgUYx7Fx/
A new version was published on GOV.UK, we need to update our links.
=> Update URL for G-Cloud 12 framework agreement

package-lock.json, package.json, schema_generator/validation.py
Trello: https://trello.com/c/lwJW7PvN/288-2-create-dos5-service-schemas
Prepare for DOS 5. I have assumed the same lots as for DOS 4.
Output: https://github.com/alphagov/digitalmarketplace-api/pull/1055
Following the [proper procedure](https://alphagov.github.io/digitalmarketplace-manual/content-and-frameworks/adding-frameworks.html#generate-service-validation-schemas-and-add-them-to-the-api) and [precedent](https://github.com/alphagov/digitalmarketplace-frameworks/pull/572)
=> Add DOS 5 validation schemata

README.md, frameworks/digital-outcomes-and-specialists-5/manifests/declaration.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/multiqSubcontracting.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/subcontracting.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/subcontracting30DayPayments.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/subcontractingInvoicesPaid.yml, package-lock.json, package.json
Trello: https://trello.com/c/Oqg9AUup/328-3-update-conditional-logic-for-declaration-question-q53-for-dos5
CCS wanted us to make some changes to this question for DOS 5. If a supplier says they use subcontractors, show them two additional questions.
We've manually checked that the questions seem to appear when expected.
Known issues outstanding (to solve in future PRs):
1. The number field isn't being validated
2. The grey bar next to the second condition question is over-long
3. We don't yet know what the pass condition is (if any) for the two new questions
=> Update logic for subcontracting questions

package-lock.json, package.json, requirements.txt, tests/test_content.py
Supplier frontend is already using v7.22.0, so it should be safe to update the frameworks repo as well.
Modify test to be able to strip out more complex paragraph tags.
=> Pull latest version of content loader and utils

frameworks/digital-outcomes-and-specialists-5/manifests/edit_service.yml, frameworks/digital-outcomes-and-specialists-5/manifests/edit_service_as_admin.yml, frameworks/digital-outcomes-and-specialists-5/manifests/edit_submission.yml, frameworks/digital-outcomes-and-specialists-5/questions/services/labPrice.yml, frameworks/digital-outcomes-and-specialists-5/questions/services/labTime.yml, package-lock.json, package.json
Ticket: https://trello.com/c/7dN6Hpva/290-2-add-hoursforprice-field-to-pricing-input-component-in-supplier-frontend
See also this change https://docs.google.com/spreadsheets/d/1FNGwe56myW2ddO6XQUtex209TJQ2Ub99PTzcWxpejsQ/edit#gid=866429329&range=D109
`hours_for_price` for the pricing input doesn't work with the new pricing field from alphagov/digitalmarketplace-supplier-frontend#1222, so we instead make it two questions.
=> Change labPrice in DOS5 into two questions

frameworks/digital-outcomes-and-specialists-5/manifests/declaration.yml, frameworks/digital-outcomes-and-specialists-5/messages/become-a-supplier.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/MI.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/civilServiceValues.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/conflictOfInterest.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/distortedCompetition.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/environmentalSocialLabourLaw.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/helpBuyersComplyTechnologyCodesOfPractice.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/modernSlaveryStatement.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/modernSlaveryStatementOptional.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/publishContracts.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/safeguardOfficialInformation.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/safeguardPersonalData.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/serviceStandard.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/subcontracting30DayPayments.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/taxEvasion.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/termsAndConditions.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/termsOfParticipation.yml, frameworks/digital-outcomes-and-specialists-5/questions/declaration/witheldSupportingDocuments.yml, frameworks/digital-outcomes-and-specialists-5/questions/services/accessibleApplicationsOutcomes.yml, frameworks/digital-outcomes-and-specialists-5/questions/services/openStandardsPrinciples.yml, frameworks/g-cloud-12/messages/become-a-supplier.yml, package-lock.json, package.json
Ticket: https://trello.com/c/dz7qu083/425-2-ensure-hardcoded-html-in-dos-framework-application-content-has-appropriate-design-system-styles
Makes sure we're using [GOV.UK Design System styles](https://design-system.service.gov.uk/styles/typography/) in DOS5 application content. Mostly making sure that links have the proper class. We should look at if there's some way we can make this easier by having the content loader add all the open in new tab attributes, instead of having to copy and paste for each link.
I also updated the 'become a supplier' message for G12 to make sure the content on that page is consistent.
There are still a few HTML elements in DOS5 brief responses content which I didn't update because it's hard to test that at this point.
=> Add GOV.UK Design System styles to HTML elements in DOS5 content

frameworks/digital-outcomes-and-specialists-5/metadata/copy_services.yml, package-lock.json, package.json, tests/test_metadata.py
https://trello.com/c/rYwa42rs/1954-error-messages-dos5
We were erroneously copying some questions from DOS4 which had been deleted in DOS5 which caused users to experience `400` errors when attempting to save services.
=> Exclude fields from DOS5 copying

tests/test_metadata.py
Refactors the tests for copy service framework metadata, and adds a new test that checks if things are missing from questions_to_exclude that should be present. This should reduce the chances of the issues we saw in https://trello.com/c/rYwa42rs/1954-error-messages-dos5.
=> Refactor metadata tests

CHANGELOG.md, frameworks/digital-outcomes-and-specialists-4/search_mappings/briefs.json, frameworks/digital-outcomes-and-specialists-5/search_mappings/briefs.json, frameworks/g-cloud-12/search_mappings/services.json, package-lock.json, package.json, schema_generator/search.py, scripts/generate-search-config.py
Ticket: https://trello.com/c/Yh8uyxvF/2102-migrate-elasticsearch-on-preview
We want to be able to generate search mappings from the frameworks repo with the changes needed for Elasticsearch 7.
New features
------------
- You can now use the G-Cloud 12 and DOS4/5 search mappings with Elasticsearch 7
Breaking changes
----------------
- You can no longer use G-Cloud 12 and DOS4/5 search mappings with Elasticsearch 6
=> Backport mapping changes from alphagov/digitalmarketplace-search-api#272

frameworks/digital-outcomes-and-specialists-5/questions/brief-responses/availability.yml, package-lock.json, package.json
Although this question asks for a simple date, it is a text question. It has been like this since it's initial commit to DOS1 [1]; I can find no evidence explaining why this question is not a date question.
To try and make it easier for users to enter a valid date this commit changes the question type to date for DOS5; this will not affect brief responses from previous frameworks and since DOS5 isn't live yet it shouldn't cause any issues with that framework (which is why I've called this a patch version change rather than a breaking change).
Hopefully this change will not be a problem going forward, although it will be interesting to see if anyone has been relying on this accepting input that is not a date.
[1]:
https://github.com/alphagov/digitalmarketplace-frameworks/commit/43edb2c4b64c …
=> Change brief responses availability question to date type

frameworks/digital-outcomes-and-specialists-4/questions/brief-responses/availability.yml, frameworks/digital-outcomes-and-specialists-4/questions/brief-responses/dayRate.yml, frameworks/digital-outcomes-and-specialists-4/questions/brief-responses/essentialRequirements.yml, frameworks/digital-outcomes-and-specialists-4/questions/brief-responses/essentialRequirementsMet.yml, frameworks/digital-outcomes-and-specialists-4/questions/brief-responses/niceToHaveRequirements.yml, frameworks/digital-outcomes-and-specialists-5/questions/brief-responses/availability.yml, frameworks/digital-outcomes-and-specialists-5/questions/brief-responses/dayRate.yml, frameworks/digital-outcomes-and-specialists-5/questions/brief-responses/essentialRequirements.yml, frameworks/digital-outcomes-and-specialists-5/questions/brief-responses/essentialRequirementsMet.yml, frameworks/digital-outcomes-and-specialists-5/questions/brief-responses/niceToHaveRequirements.yml, package-lock.json, package.json
https://trello.com/c/13tOvxuu/285-2-replace-content-loader-form-macros-in-brief-responses-frontend
We're trying to remove as much hard-coded HTML from these questions as we can.
In some instances, it is unavoidable, and this is causing a bug: https://trello.com/c/OMcXpf8k/1476-content-loader-can-generate-invalid-html
However, that is out of scope for this ticket.
=> Brief response markdown tweaks

frameworks/digital-outcomes-and-specialists-4/questions/brief-responses/dayRate.yml, frameworks/digital-outcomes-and-specialists-5/questions/brief-responses/dayRate.yml, package-lock.json, package.json
The headings made the question difficult to parse at a glance. Removing them places more focus on the
question and the input, rather than so much emphasis on the advice.
=> Remove headings from Day Rate question advice

.github/workflows/test.yml, schema_generator/validation.py, tests/test_generate_validation_schema.py
Ticket: https://trello.com/c/LY1lCPUt/291-1-fix-schema-generator-in-frameworks-repo
Adding `{{ item }}` to dynamic list question error messages in #656 caused validation schema generation to fail because `item` was not present in the template context.
This PR adds `item` to the context for all questions; it is a bit of a hack but is the only fix I could think of.
Also, it was a bit worrying that we didn't notice that the schema generator was broken when we merged #656, so I've also added some functional tests of the schema generation scripts. I tested that this functional test fails as expected if the fix is not present.
=> Fix bug in validation schema generator

frameworks/digital-outcomes-and-specialists-5/messages/urls.yml, package.json
https://trello.com/c/75hbcRW8/607-2-implement-dos-5-e-signature
N.B. There is no call off contract URL for this framework. I think this is not linked to so _should_ be OK.
=> Update DOS5 URLs

frameworks/digital-outcomes-and-specialists-4/manifests/display_brief.yml, frameworks/digital-outcomes-and-specialists-5/manifests/display_brief.yml, package.json
https://trello.com/c/YZJhCqq2/238-3-dos5-public-brief-page-add-mandatory-assessment-method-to-summary-text
Rather than hardcoding this logic in the app, as previously in: https://github.com/alphagov/digitalmarketplace-buyer-frontend/blob/37f0d7da87b41843f809c107b7cd376d6487308f/app/main/helpers/brief_helpers.py#L33-L45 we want to move this to the frameworks repository.
=> Add template logic to 'How evaluated' description

frameworks/digital-outcomes-and-specialists-5/questions/brief-responses/availability.yml, frameworks/digital-outcomes-and-specialists-5/questions/briefs/awardedContractStartDate.yml, frameworks/digital-outcomes-and-specialists-5/questions/briefs/startDate.yml, package-lock.json, package.json
While testing DOS5 journeys before go-live we noticed that the example dates we give when creating or responding to a brief are in 2020. We want these dates to be relatable to our users, so change them to 2021.
https://trello.com/c/bQUiYaju/702-05-update-date-examples-to-2021
=> Change DOS5 example dates to 2021 

frameworks/digital-outcomes-and-specialists-5/questions/briefs/additionalTermsOutcomesSpecialists.yml, frameworks/digital-outcomes-and-specialists-5/questions/briefs/additionalTermsParticipants.yml, package-lock.json, package.json
We have a new [landing page](https://www.gov.uk/guidance/digital-outcomes-and-specialists-5-legal-documents) for all DOS5 legal documents, so direct buyers to this on the additional terms questions.
https://trello.com/c/fjMThOjv/703-1-send-buyers-to-the-correct-dos5-standard-contract-link
=> Update DOS5 contract link to new legal documents landing page

frameworks/digital-outcomes-and-specialists-5/messages/urls.yml, package-lock.json, package.json
For DOS5 the call-off contract is split into two documents - Joint Schedules and Call-Off Schedules. We want buyers and suppliers to be able to find both of these, so link to the DOS5 legal documents landing page rather than a specific document.
=> Add call off contract URL

package-lock.json, package.json
- The lot descriptions for DOS5 have been updated for the new choose a lot journey (#674)
- The default branch has been renamed to `main` (#672)
- You can now use invoke instead of make (#675)
=> Version bump (minor) to 18.2.0

frameworks/digital-outcomes-and-specialists-5/messages/become-a-supplier.yml, frameworks/g-cloud-12/messages/become-a-supplier.yml, package-lock.json, package.json
Ticket: https://trello.com/c/Ajssa0oq/890-3-update-content-for-create-a-supplier-account-journey
Tweaks the content on the 'Become a supplier' page to make it clear when suppliers can create an account, and also adds a heading to separate the content better.
I couldn't figure out how to add the headings in the supplier frontend rather than here, because we don't have the framework family name in the framework object or in the framework content.
=> Update content for create a supplier account journey

requirements-dev.in, requirements-dev.txt
Follow-up to #682 (suggested in https://github.com/alphagov/digitalmarketplace-frameworks/pull/682#discussion_r618167116 by @lfdebrux) 
We don't need to specify versions now we're using pip-tools.
=> unpin requirements

frameworks/digital-outcomes-and-specialists-5/manifests/display_brief.yml, frameworks/digital-outcomes-and-specialists-5/manifests/edit_brief.yml, frameworks/digital-outcomes-and-specialists-5/questions/briefs/employmentStatus.yml, package-lock.json, package.json
HMRC has strongly encouraged Public Sector Bodies (PSB)  to advertise roles as inside or outside IR35 in order to set the expectations of suppliers from the outset. The  HMRC off-payroll rules come [into force](https://www.gov.uk/guidance/april-2020-changes-to-off-payroll-working-for-intermediaries) in April 2021. As such, the DOS team has determined that all published (outcomes and specialist) opportunities will need clear indication if they are inside or outside of IR35. 
Add a new question into the buyer journey that asks our buyers the IR35 status of an opportunity.
The wording of the question has been approved by CCS and the Tax Centre of Excellence at HMRC - see https://trello.com/c/apbMZmVd/12-5-confirm-wording-for-the-new-ir35-question …
=> Add employment status question to DOS buyer journey

frameworks/g-cloud-13/metadata/following_framework.yml, frameworks/g-cloud-13/questions/declaration/canProvideFromDayOne.yml, frameworks/g-cloud-13/questions/declaration/understandHowToAskQuestions.yml, package-lock.json, package.json
So that it's obvious they're still placeholders and we can more easily spot them in content review. I've set the G-Cloud 14 coming year as 2525 as well, rather than the more logical 2526, so if we do a search for `2525` when checking we've found all the dates it'll show up.
I ran `rg 202[12345] frameworks/g-cloud-13/` from the repo root to verify there were no more dates.
https://trello.com/c/0cIG51Pk/70-2-clone-framework-content
=> Set G-Cloud 13 dates to 2525

schema_generator/validation.py
We know G-Cloud 13 will have a fourth lot, but we don't know exactly what that will be at the moment. Therefore, add the new framework to the schema generation script using the same lots as G-Cloud 12 so we can test things out locally.
https://trello.com/c/3SULJbtw/78-1-g-cloud-13-filter-a-person-from-lots-1-2-3-pricing-question
=> Add G-Cloud 13 to validation schema script

frameworks/g-cloud-13/metadata/copy_services.yml
This PR simply excludes de price question from G-cloud 13 for lot 1, 2 and 3, regardless of the unit chosen. Not the most user friendly choice but there was no nice way to filter out only day rates and this ensures the data copies is consistent, at least.
https://trello.com/c/GcJG9TPK/79-3-g-cloud-13-handle-pricing-question-on-services-copied-from-previous-frameworks
=> Exclude price question from G-Cloud 13
