requirements_for_test.txt
tests/schemas/question.json
tests/test_all.py

This adds a test that verifies the schema of the question files. The schema provided in this pull request only verifies the question and type fields. The intention is that we would build on it.

Add basic schema checking for questions

---

g6/supportAvailability.yml

See: https://www.pivotaltracker.com/story/show/97883196

[#97883196] Fix typo 'availablility' --> 'availability'

---

g6/dataAtRestProtections.yml
g6/dataProtectionBetweenServices.yml
g6/dataProtectionBetweenUserAndService.yml
g6/dataProtectionWithinService.yml
g6/deviceAccessMethod.yml
g6/serviceManagementModel.yml

This is in line with the changes agreed with Tony R prior to the G6 SSP data export.

Change some questions from radios to checkboxes

---

g7_declaration/SQ3-1k.yml

From John Williams:
> **Exactly the same as current q56, we need to add a why box for questions 41-53**
> If you responded yes to any of questions 41-53, please provide details of any
> mitigating factors that you think should be taken into consideration.

Add SQ3-1k

---

g7_declaration/PR4.yml
g7_declaration/SQ1-1a.yml
g7_declaration/SQ1-1n.yml
g7_declaration/SQ1-1o.yml

a few suggested edits from CCS.

Ccs edits 120815

---

g7_declaration/SQ1-1cii.yml
g7_declaration/SQ1-1i-i.yml
g7_declaration/SQ1-1i-ii.yml
g7_declaration/SQ1-1j-ii.yml
g7_declaration/SQE2a.yml

- more number reference changes to follow.

Number references in questions and updated business registration question

---

g6/elasticCloud.yml
g6/guaranteedResources.yml
g6/persistentStorage.yml
g6/serviceBenefits.yml
g6/serviceFeatures.yml
g6/serviceSummary.yml
g6/supportForThirdParties.yml
g6/vendorCertifications.yml

Updated question hints to reflect answers to clarification questions and main problems experienced in user research.

G7 hint text updates

---

g7_declaration/AQA3.yml
g7_declaration/PR1.yml
g7_declaration/PR2.yml
g7_declaration/SQ5-2a.yml
g7_declaration/SQC2.yml
g7_declaration/SQE2a.yml

CCS have updated their attachment numbering. These commits update the numbers and some hint text.

Update attachment numbers and hints

---

g7_declaration/AQA3.yml
g7_declaration/PR1.yml
g7_declaration/PR2.yml
g7_declaration/PR5.yml
g7_declaration/SQA2.yml
g7_declaration/SQC2.yml

added links where we previous had 'add link'

Add supplier pack links

---

g7_declaration/AQA3.yml
g7_declaration/PR1.yml
g7_declaration/PR2.yml
g7_declaration/SQC2.yml

See: https://www.pivotaltracker.com/story/show/102170518
The location of the supplier pack has changed - this updates links to the new location.

[#102170518] Update supplier pack links

---

g7_declaration/SQ2-1f.yml
g7_declaration/SQ2-1ghijklmn.yml
g7_declaration/SQC3.yml

added hint text to be consistent with earlier similar questions.

Declaration run through edits 280815

---

frameworks/digital-outcomes-and-specialists/manifests/declaration.yml

--
This is a requirement of [the story](https://www.pivotaltracker.com/story/show/105181036).
@superroz can you check the wording?

Remind users they can edit their declaration later

---

frameworks/digital-outcomes-and-specialists/manifests/declaration.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/10WorkingDays.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/MI.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/accuratelyDescribed.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/bespokeSystemInformation.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/canProvideFromDayOne.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/contactEmailContractNotice.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/contactNameContractNotice.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/cyberEssentials.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/cyberEssentialsPlus.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/organisedCrime.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/permanentMemberOfStaff.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/publishContracts.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/requisiteAuthority.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/safeguardData.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/safeguardOfficialInformation.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/safeguardPersonalData.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/serviceStandard.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/skillsAndCapabilityAssessment.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/skillsAndResources.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/subcontractorInformation2.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/sufficientInformation.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/taxEvasion.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/technologyCodesOfPractice.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/termsAndConditions.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/tradingNames.yml

Content edits 4

---

frameworks/digital-outcomes-and-specialists/manifests/declaration.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/canProvideServices.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/governmentSecurityPrinciples.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/safeguardData.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/safeguardPersonalData.yml

Removed extra questions and merged hint text.

Content dedupe

---

frameworks/digital-outcomes-and-specialists/questions/declaration/canProvideFromDayOne.yml

Ran all the content through a spell checker. This is the only legitimate one it found.

Fix spelling mistake

---

frameworks/digital-outcomes-and-specialists/manifests/edit_submission.yml
frameworks/digital-outcomes-and-specialists/questions/services/businessAnalystDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/businessAnalystLocations.yml
frameworks/digital-outcomes-and-specialists/questions/services/deliveryManagerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/deliveryManagerLocations.yml
frameworks/digital-outcomes-and-specialists/questions/services/developerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/developerLocations.yml
frameworks/digital-outcomes-and-specialists/questions/services/example.yml
frameworks/digital-outcomes-and-specialists/questions/services/lot.yml
frameworks/digital-outcomes-and-specialists/questions/services/outcomesApproachQuestion.yml
frameworks/digital-outcomes-and-specialists/questions/services/outcomesSupplierInformation.yml
frameworks/digital-outcomes-and-specialists/questions/services/productManagerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/productManagerLocations.yml
frameworks/digital-outcomes-and-specialists/questions/services/programmeManagerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/programmeManagerLocations.yml
frameworks/digital-outcomes-and-specialists/questions/services/serviceManagerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/serviceManagerLocations.yml
frameworks/digital-outcomes-and-specialists/questions/services/specialistsApproachQuestion.yml
frameworks/digital-outcomes-and-specialists/questions/services/specialistsSupplierInformation.yml
frameworks/digital-outcomes-and-specialists/questions/services/technicalArchitectDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/technicalArchitectLocations.yml

For digital-specialists and digital-outcomes.

Add basic DOS flows

---

frameworks/digital-outcomes-and-specialists/manifests/declaration.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/employmentAgency.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/fullAccountability.yml
frameworks/digital-outcomes-and-specialists/questions/declaration/offerServicesYourselves.yml

Added 2 new questions from JW and deleted the employment question.

Employment questions

---

frameworks/digital-outcomes-and-specialists/questions/declaration/registeredAddress.yml

[#107994592] https://www.pivotaltracker.com/story/show/107994592
We want to make sure we get relatively clean address data.

Revert DOS address field in declaration

---

frameworks/digital-outcomes-and-specialists/questions/services/deliveryTypes.yml
frameworks/digital-outcomes-and-specialists/questions/services/securityTypes.yml
frameworks/digital-outcomes-and-specialists/questions/services/softwareDevelopmentTypes.yml
frameworks/digital-outcomes-and-specialists/questions/services/supportAndOperationsTypes.yml
frameworks/digital-outcomes-and-specialists/questions/services/testingAndAuditingTypes.yml
frameworks/digital-outcomes-and-specialists/questions/services/userExperienceAndDesignTypes.yml

* simplified some of the types
* replaced all the '/' with 'and'
* removed the things in brackets (this content will be added to the supporting information)

Updated outcomes types content

---

frameworks/digital-outcomes-and-specialists/questions/services/agileCoachDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/businessAnalystDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/communicationsManagerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/contentDesignerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/deliveryManagerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/designerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/developerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/labPrice.yml
frameworks/digital-outcomes-and-specialists/questions/services/performanceAnalystDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/portfolioManagerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/productManagerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/programmeManagerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/qualityAssuranceDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/securityConsultantDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/serviceManagerDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/technicalArchitectDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/userResearcherDayRate.yml
frameworks/digital-outcomes-and-specialists/questions/services/webOperationsDayRate.yml
scripts/generate_dos_questions.sh

- Add DOS price validations to generator
- Add DOS price validations for specialist day rates
- Add price validations for labs

Add dos price validations

---

frameworks/digital-outcomes-and-specialists/manifests/declaration.yml
frameworks/digital-outcomes-and-specialists/messages/homepage-sidebar.yml

https://www.pivotaltracker.com/story/show/108938292

[#108938292] Update DOS closing date

---

frameworks/digital-outcomes-and-specialists/manifests/edit_submission.yml
frameworks/digital-outcomes-and-specialists/questions/services/dataProtocols.yml
frameworks/digital-outcomes-and-specialists/questions/services/labAddressBuilding.yml

* fixed name on ```dataProtocols.yml```
* fixed lab address question by removing hint and changing question to ‘Lab address’

Content updates

---

frameworks/digital-outcomes-and-specialists/questions/services/supportAndOperationsTypes.yml

Swapped Service desk and Systems administration

Make in alphabetical order

---

frameworks/digital-outcomes-and-specialists/questions/services/securityTypes.yml

Moved IT health check into correct position.

Make alphabetical order

---

frameworks/digital-outcomes-and-specialists/questions/services/security.yml

Added Cyber security hint text

Add hint text

---

frameworks/digital-outcomes-and-specialists/questions/services/programmeManager.yml

Add hint text to programme manager

Add a hint

---

frameworks/digital-outcomes-and-specialists/questions/services/supportAndOperationsTypes.yml

Added hint text for Service desk, original hint text duplicated Network administration hint text

Add correct Service desk hint text

---

frameworks/digital-outcomes-and-specialists/manifests/edit_brief_response.yml

Because all questions have to be responded to on a single page.

Brief responses should be all in one section

---

requirements.txt

This allows the schemas to be generated properly with `location` fields.

Bump utils version to 18.0.0

---

frameworks/digital-outcomes-and-specialists/questions/brief-responses/respondToEmailAddress.yml
schema_generator/__init__.py
schemas/questions.json

This allows email validation to be added to the auto-generated JSON schemas.

Add new `email` question type

---

frameworks/g-cloud-8/manifests/declaration.yml
frameworks/g-cloud-8/questions/declaration/AQA3.yml
frameworks/g-cloud-8/questions/declaration/PR1.yml
frameworks/g-cloud-8/questions/declaration/SQC2.yml

Initial changes for the G-Cloud 8 supplier declaration made during training with Tom

G cloud 8 supplier declaration - Cath training with Tom

---

frameworks/digital-outcomes-and-specialists/questions/briefs/numberOfSuppliersOutcomes.yml
frameworks/digital-outcomes-and-specialists/questions/briefs/numberOfSuppliersParticipants.yml
frameworks/digital-outcomes-and-specialists/questions/briefs/numberOfSuppliersSpecialists.yml

change 'How many suppliers/specialists you want to evaluate' to 'How many suppliers/specialists will be evaluated' so the question makes sense in the opportunity page and is consistent with how we asked questions elsewhere.

Reword question for number of suppliers

---

frameworks/digital-outcomes-and-specialists/questions/briefs/priceCriteria.yml

As requested in this story: https://www.pivotaltracker.com/story/show/118286875

Updates to 'capped time and materials' description

---

frameworks/g-cloud-8/questions/declaration/accuratelyDescribed.yml
frameworks/g-cloud-8/questions/declaration/appropriateTradeRegistersNumber.yml
frameworks/g-cloud-8/questions/declaration/canProvideCloudServices.yml
frameworks/g-cloud-8/questions/declaration/firstRegistered.yml
frameworks/g-cloud-8/questions/declaration/nameOfOrganisation.yml
frameworks/g-cloud-8/questions/declaration/readUnderstoodGuidance.yml
frameworks/g-cloud-8/questions/declaration/servicesHaveOrSupport.yml
frameworks/g-cloud-8/questions/declaration/skillsAndResources.yml
frameworks/g-cloud-8/questions/declaration/subcontracting.yml
frameworks/g-cloud-8/questions/declaration/tradingStatusOther.yml

Small changes for consistency, alignment to DOS and some typos

G cloud 8 supp decl small fixes

---

frameworks/g-cloud-8/messages/homepage-sidebar.yml

Fix G-Cloud message

---

frameworks/digital-outcomes-and-specialists-2/questions/declaration/termsAndConditions.yml
frameworks/digital-outcomes-and-specialists-2/questions/declaration/termsOfParticipation.yml

Removing links to the ZIP file and pointing to the overview page instead

DOS2 remove zip links

---

schema_generator/__init__.py

We want the script to generate schemas for briefs as well as services.

Generate DOS2 briefs and responses schemas

---

frameworks/digital-outcomes-and-specialists-2/questions/briefs/locationOutcomes.yml
frameworks/digital-outcomes-and-specialists-2/questions/briefs/locationParticipants.yml
frameworks/digital-outcomes-and-specialists-2/questions/briefs/locationSpecialists.yml
frameworks/digital-outcomes-and-specialists/questions/briefs/locationOutcomes.yml
frameworks/digital-outcomes-and-specialists/questions/briefs/locationParticipants.yml
frameworks/digital-outcomes-and-specialists/questions/briefs/locationSpecialists.yml

Text changes to bring things inline with #323 and fixes the security issue with links for DOS questions.
Fixes https://www.pivotaltracker.com/n/projects/1884593/stories/134137657

Updated 'view region' to 'view location' and fixed links.

---

README.md

Does this make sense @allait ?

Mention 'bower link' in README as it's very useful

---

frameworks/g-cloud-9/manifests/declaration.yml

GCloud 9 supplier declaration

---

frameworks/g-cloud-9/questions/services/governmentSecurityClearances.yml

Corrected question name.
This one's not high priority, MVP can launch without it.
Ticket: https://trello.com/c/mWvxIPFG/398-review-question-names

Corrected question name

---

.gitignore
default.nix
local.example.nix
setup.cfg

Much like all the other initial default.nix PRs.

add initial default.nix

---

Makefile

- everything else got switched already.

Makefile should produce a Py3K environment.

---

schema_generator/validation.py

This has been run already and schemas added to API in https://github.com/alphagov/digitalmarketplace-api/pull/729

Generate schemas for G10 and DOS3

---

frameworks/digital-outcomes-and-specialists-3/manifests/declaration.yml
frameworks/digital-outcomes-and-specialists-3/questions/declaration/employmentStatus.yml
frameworks/digital-outcomes-and-specialists-3/questions/declaration/terrorism.yml
package.json

For[ this trello ticket.](https://trello.com/c/uRNZWEVm)
One immaterial change to a question about terrorism.
A new question regarding employment status.
The new question will require some though about how we copy declarations
between frameworks, however that's for a different ticket.
---
---
---

Update DOS3 declaration questions

---

frameworks/digital-outcomes-and-specialists-3/manifests/edit_service.yml
frameworks/digital-outcomes-and-specialists-3/manifests/edit_service_as_admin.yml
frameworks/digital-outcomes-and-specialists-3/manifests/edit_submission.yml
frameworks/digital-outcomes-and-specialists-3/questions/briefs/specialistRole.yml
frameworks/digital-outcomes-and-specialists-3/questions/services/dataArchitect.yml
frameworks/digital-outcomes-and-specialists-3/questions/services/dataArchitectDayRate.yml
frameworks/digital-outcomes-and-specialists-3/questions/services/dataArchitectLocations.yml
frameworks/digital-outcomes-and-specialists-3/questions/services/dataEngineer.yml
frameworks/digital-outcomes-and-specialists-3/questions/services/dataEngineerDayRate.yml
frameworks/digital-outcomes-and-specialists-3/questions/services/dataEngineerLocations.yml
frameworks/digital-outcomes-and-specialists-3/questions/services/dataScientist.yml
frameworks/digital-outcomes-and-specialists-3/questions/services/dataScientistDayRate.yml
frameworks/digital-outcomes-and-specialists-3/questions/services/dataScientistLocations.yml
package.json

For [this trello ticket.](https://trello.com/c/VkAyVrzT)
Adds required questions and manifest entries for data architects,
engineers and scientists.

Add new specialist roles for DOS3

---

frameworks/digital-outcomes-and-specialists-2/questions/briefs/additionalTermsOutcomesSpecialists.yml
frameworks/digital-outcomes-and-specialists-2/questions/briefs/additionalTermsParticipants.yml
frameworks/digital-outcomes-and-specialists-3/questions/briefs/additionalTermsOutcomesSpecialists.yml
frameworks/digital-outcomes-and-specialists-3/questions/briefs/additionalTermsParticipants.yml

Ticket: https://trello.com/c/TujeCS5C/367-update-link-from-dos1-to-dos2-call-off-contract-in-additional-terms-and-conditions-section

Update links to standard contracts in DOS2 and DOS3

---

frameworks/digital-outcomes-and-specialists-3/questions/declaration/canProvideFromDayOne.yml
frameworks/digital-outcomes-and-specialists-3/questions/declaration/understandHowToAskQuestions.yml
package.json

For [this trello ticket.](https://trello.com/c/qRd3qmjg)

Update DO3 declaration with dates

---

frameworks/digital-outcomes-and-specialists-3/questions/declaration/civilServiceValues.yml
frameworks/digital-outcomes-and-specialists-3/questions/declaration/publishContracts.yml
frameworks/digital-outcomes-and-specialists-3/questions/declaration/safeguardOfficialInformation.yml
frameworks/digital-outcomes-and-specialists-3/questions/declaration/safeguardPersonalData.yml
frameworks/digital-outcomes-and-specialists-3/questions/declaration/serviceStandard.yml
package.json

For [this trello ticket.](https://trello.com/c/yYTrmIk3)
Some links not opening in new tabs, and a couple of out of date link.

Fix bugs in DOS3 declaration questions

---

frameworks/g-cloud-11/manifests/edit_submission.yml
frameworks/g-cloud-11/questions/declaration/mitigatingFactors3.yml
frameworks/g-cloud-11/questions/declaration/modernSlaveryStatement.yml
frameworks/g-cloud-11/questions/declaration/modernSlaveryStatementOptional.yml
frameworks/g-cloud-11/questions/services/cloudDeploymentModel.yml
frameworks/g-cloud-11/questions/services/documentation.yml
frameworks/g-cloud-11/questions/services/documentationAccessibility.yml
frameworks/g-cloud-11/questions/services/documentationAccessibilityDescription.yml
frameworks/g-cloud-11/questions/services/emailOrTicketingSupportAccessibility.yml
frameworks/g-cloud-11/questions/services/energyEfficientDatacentres.yml
frameworks/g-cloud-11/questions/services/energyEfficientDatacentresDescription.yml
frameworks/g-cloud-11/questions/services/multiqDocumentation.yml
frameworks/g-cloud-11/questions/services/multiqEnergyEfficiency.yml
frameworks/g-cloud-11/questions/services/multiqServiceInterface.yml
frameworks/g-cloud-11/questions/services/publicSectorNetworksTypes.yml
frameworks/g-cloud-11/questions/services/serviceInterface.yml
frameworks/g-cloud-11/questions/services/serviceInterfaceAccessibility.yml
frameworks/g-cloud-11/questions/services/serviceInterfaceDescription.yml
frameworks/g-cloud-11/questions/services/webChatSupportAccessibility.yml
frameworks/g-cloud-11/questions/services/webInterfaceAccessibility.yml
package.json

Trello: https://trello.com/c/x5GVLSkq/384-implement-changes-for-legislation-changes-in-application-questions
Service question updates from G11.
Also minor declaration tweaks following on from v13.8.0.
Used to generate schemas for https://github.com/alphagov/digitalmarketplace-api/pull/903.

G11 service updates

---

frameworks/digital-outcomes-and-specialists-3/questions/brief-responses/respondToEmailAddress.yml

https://trello.com/c/c3mRFQNT/424-look-at-validation-on-briefresponsesdata-respondtoemailaddress

Add hint text - formatting multiple email addresses

---

frameworks/digital-outcomes-and-specialists-4/manifests/declaration.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/GAAR.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/bankrupt.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/confidentialInformation.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/conflictOfInterest.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/conspiracy.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/corruptionBribery.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/distortedCompetition.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/distortingCompetition.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/environmentalSocialLabourLaw.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/fraudAndTheft.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/graveProfessionalMisconduct.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/influencedContractingAuthority.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/misleadingInformation.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/mitigatingFactors3.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/modernSlaveryReportingRequirements.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/modernSlaveryStatement.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/modernSlaveryStatementOptional.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/modernSlaveryTurnover.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/multiqModernSlavery.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/organisedCrime.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/outsideIR35.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/seriousMisrepresentation.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/significantOrPersistentDeficiencies.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/terrorism.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/unfairCompetition.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/unspentTaxConvictions.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/witheldSupportingDocuments.yml
package.json

https://trello.com/c/kTVN6PlQ/532-clone-dos4-content
The first of several PRs for this - content changes all supplied by Stefan but please look out for copy/paste errors, broken `href`s etc.
Copies the ModernSlavery section wholesale from G11 with no changes. We don't want to prefill this section from G11 as it includes a document upload.
One question has changed significantly (a previous 'pass' answer of `True` will now fail) - however this question is not prefilled from previous declarations, so we should be fine.

DOS4 declaration updates

---

frameworks/digital-outcomes-and-specialists-4/messages/homepage-sidebar.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/canProvideFromDayOne.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/understandHowToAskQuestions.yml
package.json

Trello: https://trello.com/c/uiyf7Wuk/115-dates-for-dos-4
These are the latest provisional dates from CCS.
This version will need to be pulled into:
- Buyer FE
- Supplier FE

Confirm DOS4 dates

---

frameworks/digital-outcomes-and-specialists-4/messages/homepage-sidebar.yml
package.json

Change the 'coming' message on the homepage to match the one from G11.

Update DOS4 homepage message

---

frameworks/digital-outcomes-and-specialists-4/questions/declaration/modernSlaveryStatementOptional.yml
frameworks/digital-outcomes-and-specialists-4/questions/declaration/multiqModernSlavery.yml
package.json

Copy-pasted from G11, whoops!
Will need pulling in to Supplier FE.

DOS4 Modern Slavery question content fix

---

frameworks/digital-outcomes-and-specialists-4/questions/services/openStandardsPrinciples.yml
package.json

Shorten the open standards principles question for DOS4

---

frameworks/digital-outcomes-and-specialists-4/questions/briefs/technicalCompetenceCriteriaOutcomes.yml
frameworks/digital-outcomes-and-specialists-4/questions/briefs/technicalCompetenceCriteriaParticipants.yml
frameworks/digital-outcomes-and-specialists-4/questions/briefs/technicalCompetenceCriteriaSpecialists.yml
package.json

https://trello.com/c/PhPYo3Ha/318-update-technical-competence-criteria-content
Request from CCS to add in this text for buyers (see below) - copy checked by Stefan.

Add guidance for scoring technical competence examples

---

default.nix

default.nix: add GIT_SSL_CAINFO

---

frameworks/g-cloud-12/questions/services/serviceDefinitionDocumentURL.yml
package.json
schema_generator/validation.py

https://trello.com/c/VLjBsVoc/257-service-question-change-make-servicedefinitiondocumenturl-mandatory
Make service definition document mandatory

257-service-question-change-make-servicedefinitiondocumenturl-mandatory

---

frameworks/g-cloud-12/questions/declaration/servicesHaveOrSupportCloudHostingCloudSoftware.yml
frameworks/g-cloud-12/questions/declaration/servicesHaveOrSupportCloudSupport.yml
package-lock.json
package.json
schemas/questions.json
tests/test_generate_assessment_schema.py

https://trello.com/c/EoMme9Md/258-update-questions-in-frameworks-repo-2
Update first 2 declaration questions for G12 to error

258-update-questions-in-frameworks-repo-2

---

frameworks/g-cloud-12/questions/declaration/servicesHaveOrSupportCloudHostingCloudSoftware.yml
frameworks/g-cloud-12/questions/declaration/servicesHaveOrSupportCloudSupport.yml
package.json

As per @NoraGDS s comments:
> Suggest the Yes doesn't need quotation marks
Could we include a 'to' before the second question:
You need to answer Yes to either this question or to question 2/1.

318-content-check-for-new-error-messages-for-new-declaration-questions

---

frameworks/g-cloud-12/metadata/copy_services.yml
package-lock.json
package.json

https://trello.com/c/OZT4aPjn/367-copying-services-some-missing-fields
I missed some fields last time 🤦‍♀ alphagov/digitalmarketplace-frameworks#609
For G13 we are going to do this differently to avoid this situation happening again - I will create a tech debt card: https://trello.com/c/WBjRZd14/1290-frameworks-repo-copyservices-list-is-very-annoying
https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1196 is blocked on this PR.

Additional missing service fields

---

frameworks/g-cloud-12/questions/declaration/10WorkingDays.yml
package-lock.json
package.json

https://trello.com/c/sDLpkbEY/371-declaration-question-mentioning-electronic-signing
This has been agreed by CCS.

Change wording for e-signature on declaration question

---

frameworks/g-cloud-12/manifests/declaration.yml
package-lock.json
package.json

https://trello.com/c/hCkxDaNf/1555-change-content-on-providing-suitable-services-page

Update wording for providing suitable services

---

frameworks/digital-outcomes-and-specialists-4/questions/clarification_question/answer.yml
frameworks/digital-outcomes-and-specialists-4/questions/clarification_question/question.yml
package-lock.json
package.json

Make the error message content more in line with GOV.UK Design System guidance.

Update error messages for DOS supplier questions and answers

---

frameworks/g-cloud-12/messages/urls.yml
package.json

https://trello.com/c/Y8E1lAQM/339-update-g-cloud-12-framework-metadata-govuk-links
As confirmed by Nora. When we get the final agreement PDF tomorrow, we'll update this PR and then merge and release.

Add the correct links for G-Cloud 12

---

frameworks/digital-outcomes-and-specialists-5/questions/services/agileCoachDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/businessAnalystDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/communicationsManagerDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/contentDesignerDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/dataArchitectDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/dataEngineerDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/dataScientistDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/deliveryManagerDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/designerDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/developerDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/performanceAnalystDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/portfolioManagerDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/productManagerDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/programmeManagerDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/qualityAssuranceDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/securityConsultantDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/serviceManagerDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/technicalArchitectDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/userResearcherDayRate.yml
frameworks/digital-outcomes-and-specialists-5/questions/services/webOperationsDayRate.yml
package-lock.json
package.json

Trello: https://trello.com/c/WlpUAQZe/327-1-update-supplier-fe-content-for-dos5-application-journey
Update as recommended by accessibility review.

Use 'a day' instead of 'per day' for DOS 5

---

frameworks/digital-outcomes-and-specialists-5/messages/homepage-sidebar.yml
package-lock.json
package.json

Trello: https://trello.com/c/wRwnyTrg/433-update-dos-5-dates

Fix DOS 5 closing date

---

frameworks/digital-outcomes-and-specialists-5/questions/declaration/mitigatingFactors.yml
frameworks/digital-outcomes-and-specialists-5/questions/declaration/mitigatingFactors3.yml
frameworks/digital-outcomes-and-specialists-5/questions/declaration/modernSlaveryStatement.yml
frameworks/digital-outcomes-and-specialists-5/questions/declaration/modernSlaveryStatementOptional.yml
frameworks/digital-outcomes-and-specialists-5/questions/declaration/safeguardPersonalData.yml
package-lock.json
package.json

GDS style says we should avoid using please where possible.

Remove please from DOS5 where possible

---

frameworks/digital-outcomes-and-specialists-5/manifests/declaration.yml
frameworks/digital-outcomes-and-specialists-5/manifests/edit_submission.yml
frameworks/digital-outcomes-and-specialists-5/questions/declaration/conspiracy.yml
frameworks/digital-outcomes-and-specialists-5/questions/declaration/corruptionBribery.yml
frameworks/digital-outcomes-and-specialists-5/questions/declaration/modernSlaveryStatementOptional.yml
frameworks/digital-outcomes-and-specialists-5/questions/declaration/terrorism.yml
package-lock.json
package.json

Trello: https://trello.com/c/KZSxuTf1/476-last-minute-dos-5-content-updates
Apply [changes requested by CCS](https://docs.google.com/document/d/1_56qeF7dKa3wtX3zBAYk4WlpjOdTKqTjz8CpVZmMC9k)
This covers all the requested changes in the doc with one exception. The misaligned question in `How you’ll deliver your services` is due to the empty question in `multiqSubcontracting.yml`. I can't see an easy way of fixing this, so we're just going to have to live with it.

Minor DOS 5 content updates

---

frameworks/digital-outcomes-and-specialists-5/messages/homepage-sidebar.yml
package-lock.json
package.json

Ticket: https://trello.com/c/asxyMFgq/2078-change-the-homepage-banner-regarding-dos5-closing-to-1pm-on-17th-nov

Update DOS5 closing date

---

frameworks/digital-outcomes-and-specialists-5/questions/declaration/unfairCompetition.yml
package-lock.json
package.json

We flipped the meaning of the question in ff63b37513f88f611653a158cef32174adfcfafc, but forgot to update the assessment criterion.
I've checked and this is the only one we need to fix

Switch pass criterion

---

.npmrc
README.md
package-lock.json
package.json

Patch version bump to test GitHub Actions. Also tweaks the README and the npmrc file.

Version bump (patch) to 18.1.10

---

package.json

We want to publish this package on NPM.

Remove private: true from package.json

---

.github/workflows/release.yml
tag_version.sh

https://trello.com/c/DrVWMkcZ/2169-rename-default-branches-on-our-repos-from-master-to-main

replace master instances with main

---

frameworks/g-cloud-12/questions/declaration/modernSlaveryStatement.yml
frameworks/g-cloud-12/questions/declaration/modernSlaveryStatementOptional.yml
frameworks/g-cloud-12/questions/services/pricingDocumentURL.yml
frameworks/g-cloud-12/questions/services/serviceDefinitionDocumentURL.yml
frameworks/g-cloud-12/questions/services/sfiaRateDocumentURL.yml
frameworks/g-cloud-12/questions/services/termsAndConditionsDocumentURL.yml
package-lock.json
package.json

We spotted this bug while working on content loader changes for these questions[[1]].
[1]: https://github.com/alphagov/digitalmarketplace-content-loader/pull/140

Use bulleted lists for G-Cloud 12 questions

---

frameworks/digital-outcomes-and-specialists-5/questions/briefs/employmentStatus.yml
package-lock.json
package.json

This was updated everywhere else based on feedback from the Tax Centre of Excellence, but we missed it in the question title.

Use 'contracted out service' in question title
